version: "3.3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports: 
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=orange.sp-lutsk.com
    volumes:
      - ./nginx/ssl:/etc/nginx/certs
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - orangehrm

  orangehrm:
    container_name: orangehrm
    image: orangehrm/orangehrm:latest
    restart: always
    depends_on:
      - mysql  

  mysql:
    image: mysql:5.7-debian
    restart: always
    volumes:
      - ./db_orange:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=orangehrm
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=orangehrm      
